### ISSUE TITLE
Quelques questions sur coclyco

### ISSUE THREAD

**Issue by ArchangeGabriel** [cozy/cozy-coclyco#1]
(J’espère que le français ne pose pas de problème, je me suis dit que ce serait plus simple)

Tout d’abord si je comprends bien, `coclyco` utilise directement la bibliothèque python ACME du projet `certbot` plutôt que de passer par ce dernier pour gérer l’obtention des certificats. Du coup l’installation et l’utilisation de `coclyco` en parallèle de `certbot` sur une même machine ne devrait pas poser de problème, puisque `coclyco` ne partagera (quasiment, cf. fin de message) rien avec `certbot` (notamment pas le `/etc/letsencrypt/` et le compte qu’il y a dedans) ? Pour le renew, le fait d’utiliser cron c’est le packaging sous Debian qui est comme ça, je peux mettre un timer systemd sous Arch si je veux ?

D’autre part, pour ce qui est de nginx, coclyco va créer un fichier dans `/etc/nginx/sites-available/` puis le lier dans `/etc/nginx/sites-enabled/`, donc ça suppose que le `nginx.conf` inclut ce dossier, correct ? Pareil, le challenge ACME doit être servi dans `/etc/ssl/private/acme-challenge`, donc il faut qu’il y ait le morceau de config correspondant (c’est ce que dit le README en tout cas, je vérifie juste) ? Aussi, à ce que je vois il n’y a pas de config particulière faite pour le SSL. Je ne sais pas s’il y a un moyen de spécifier sa conf SSL pour tous les blocs serveurs sur nginx (mais si oui je suis preneur), à défaut pourrait-on supposer que l’utilisateur dispose d’un `/etc/nginx/ssl.conf` à inclure automatiquement dans les vhosts ?

Enfin, ça m’amène à ma petite question sur les chemins actuellement codés en dur : ce serait possible de les modifier via un fichier de conf genre `/etc/cozy/coclyco.conf` (ou .yaml/.yml si on fait du YAML, ou autre) ? Typiquement, je voudrais que la clé et les certs soient dans `/etc/cozy/ssl/`, que le dossier utilisé pour le challenge ACME soit `/var/lib/letsencrypt/acme/`.

Merci d’avance !

**Comment by ArchangeGabriel** [comment]
Ping @aeris. ;)

**Comment by aeris** [comment]
Oh ! J’avais répondu à ce post pourtant /o\ J’ai du raté l’envoi…
Je reprend du coup 😄

> Du coup l’installation et l’utilisation de coclyco en parallèle de certbot sur une même machine ne devrait pas poser de problème, puisque coclyco ne partagera (quasiment, cf. fin de message) rien avec certbot (notamment pas le /etc/letsencrypt/ et le compte qu’il y a dedans) ?

Tout à fait

> Pour le renew, le fait d’utiliser cron c’est le packaging sous Debian qui est comme ça, je peux mettre un timer systemd sous Arch si je veux ?

Oui

> D’autre part, pour ce qui est de nginx, coclyco va créer un fichier dans /etc/nginx/sites-available/ puis le lier dans /etc/nginx/sites-enabled/, donc ça suppose que le nginx.conf inclut ce dossier, correct ?

Oui

> Pareil, le challenge ACME doit être servi dans /etc/ssl/private/acme-challenge, donc il faut qu’il y ait le morceau de config correspondant (c’est ce que dit le README en tout cas, je vérifie juste) ? 

Oui, et cette config doit être chargée pour tous les vhosts.
Le plus simple, étant donné que HTTP est has-been, est d’avoir un unique vhost catch-all en :80 qui s’occupe uniquement de ACME et d’une redirection HTTP/HTTPS générique, et d’avoir tout le reste en :443. Ça évite d’avoir à intégrer le ACME challenge dans chaque vhost.

> Aussi, à ce que je vois il n’y a pas de config particulière faite pour le SSL. Je ne sais pas s’il y a un moyen de spécifier sa conf SSL pour tous les blocs serveurs sur nginx (mais si oui je suis preneur), à défaut pourrait-on supposer que l’utilisateur dispose d’un /etc/nginx/ssl.conf à inclure automatiquement dans les vhosts ?

La config TLS se passe sans problème dans un bloc `http` et non `server`, on peut donc tout configurer en une seule fois via le `nginx.conf` directement (ou un include correspondant).

> Enfin, ça m’amène à ma petite question sur les chemins actuellement codés en dur : ce serait possible de les modifier via un fichier de conf genre /etc/cozy/coclyco.conf (ou .yaml/.yml si on fait du YAML, ou autre) ?

Le répertoire des clefs & certificats est actuellement paramétrable par la variable d’env `ACME_DIRECTORY`.
https://github.com/cozy/cozy-coclyco/blob/master/cozy/coclyco/acme.py#L28
Par contre `coclyco` cherche toujours un chemin `acme-challenge` en dur dedans pour les challenges ACME
https://github.com/cozy/cozy-coclyco/blob/master/cozy/coclyco/acme.py#L34

À voir si on peut effectivement améliorer les choses à ce niveau.
