### ISSUE TITLE
Coclyco does not error when password env variable is not set

### ISSUE THREAD

**Issue by flo-dhalluin** [cozy/cozy-coclyco#2]
.. It just hangs waiting for cozy-stack to return ( but cozy stack is blocked on the password prompt...)

At least we could check that variable exists before trying to call cozy-stack. this could be a major stopper because, on my self-host, coclyco requires to be run as root ( because : r/w to /etc/ssl/private/... ), and sudo doesn't pass env variables by default.  ( so pro-tip : sudo -E ) 

Also then how  are we supposed to handle this password for the letsencrypt renew cron ?

**Comment by sblaisot** [comment]
deprecating coclyco in favor of new [installation instructions](https://docs.cozy.io/en/tutorials/selfhosting/)
