### ISSUE TITLE
"cozy-coclyco renew" should remove state storage after error.

### ISSUE THREAD

**Issue by be1** [cozy/cozy-coclyco#4]
Hello,

After launching `cozy-coclyco renew` as non-root user an error occurred on file permission (that is normal). Then restarting it as root user makes `cozy-coclyco renew` **hangs indefinitely**. I suspect cozy-coclyco waiting a pid that does not exist anymore, to finish.

**Comment by be1** [comment]
After a bit of investigation, it seems the second call to `cozy-coclyco renew` waits for a spawned command that is `cozy-stack instances ls` forever. But nothing is prompted. There should be a prompt to enter passwd I think. launching `cozy-stack instances ls` by hand asks for passwd though.

**Comment by sblaisot** [comment]
Deprecating coclyco in favor of new [installation instructions](https://docs.cozy.io/en/tutorials/selfhosting/)
