### ISSUE TITLE
Cozy & cloudflared

### ISSUE THREAD

**Issue by answer35** [cozy/cozy-coclyco#5]
Bonjour, j'espère que le français n'est pas un problème mais cela permet d'être plus sûr de mes mots :)
J'utilise actuellement Nextcloud depuis quelques années et je viens de connaître votre solution donc j'essaie de l'installer sur un proxmox de test pour le moment. J'ai pu procéder à toutes les étapes d'installation mais à partir du moment des liens DNS, je pense que j'ai un problème avec l'utilisation prévue. En effet j'utilise le tunnel cloudflared afin d'avoir une connexion à distance. Les liens générés par le DNS sont tous classés en https. Lorsque je lance la commande coclyco je reçois l'erreur du type suivant:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://cozy.mydomain/.well-known/acme-challenge/d3vphEbJ7EDJ9n0UhWJ3goTlTbc1vypcBi2amBruK7o`

J'imagine que le problème est que cloudflared génère lui-même les certificats et prépare les liens DNS en https directement, du coup je n'arrive pas à accéder aux liens par la suite.
Est-ce que des configurations ont déjà été faites en utilisant cette méthode ? Ou quelqu'un aurait assez de connaissance pour m'éclairer malgré mon manque personnel ? :)

**Comment by sblaisot** [comment]
Bonjour,
désolé pour la réponse tardive. Nous venons de publier de nouveaux paquets et de nouvelles instructions d'installation, les précédentes commençaient sérieusement à devenir obsolètes.

Je vous encourage à consulter la [documentation](https://docs.cozy.io/en/tutorials/selfhosting/) qui vous laissera probablement plus le loisir d'utiliser d'autres solutions de reverse proxy, comme cloudflare, que ne le permettait coclyco.
